before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y librxtx-java
language: java
jdk: openjdk8

notifications:
  email: true
  on_success: never
  on_failure: always

script:
 - "bash jrxtx/src/test/setup-virtual-serial-ports.sh"
