= jRxTx - The Java Serial Communication Library

jRxTx is a Java serial communication library, which provides a platform independent
serial communication API. 
The goal of jRxTx is to provide a light weight, intuitive, well documented, alternative 
API in contrast to the original http://rxtx.qbang.org/[RXTX libaray].

Imporvements of jRxTx compared to RXTX:

* light weight API.
* The Jar file is is OSGi Bundle.
* The Jar file is published on https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jrxtx%22[maven central].
* The Java build system has been moved to Gradle.
* Provide I/O streams as in java.net.Socket
* Optionally add the native libs to the jar and load the libs from the jar.


== Build jRxTx on your host system

To build jRxTx run the following command:

----
$ ./gradlew [buildLibs [-PlibTarget=<the build system e.g. i686-pc-linux-gnu>]] build 
----

The command build libs, packs the native library into the jar.

Since jRxTx builds on RXTX, you can also install librxtx-java on Debian systems, instead of packing the library to the jar, as mentioned above:

----
$ sudo apt-get install librxtx-java
----

== Licence

jRxTx is licensed under the https://raw.githubusercontent.com/openmuc/jrxtx/develop/LICENCE[LGPLv3.0] or later.
