= jRxTx - Java Serial Communication Library

jRxTx is a Java serial communication library licensed under the
LGPLv2.1 or later + linking exception. It can be used to communicate
using well known UART-based serial protocols such as RS-232, RS-422
and RS-485. The goal of jRxTx is to provide a lightweight, intuitive
and well documented API.

jRxTx wraps the popular http://rxtx.qbang.org/[RXTX library] for
which development has been discontinued. In addition to the new API,
the original RXTX API can be accessed through jRxTx. Thus jRxTx can be
used as drop-in replacement for RXTX.

Improvements of jRxTx compared to RXTX:

* Improved API (see explanation below)

* Includes Javadoc

* The Jar file is an OSGi Bundle.

* The Jar file is published on
  https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jrxtx%22[maven
  central].

* The Java build system has been moved to Gradle.

* Optionally add the native libs to the jar and load the libs from the
  jar.

== Using jRxTx

jRxTx consists of a Java library and a native library written in
C. The Java library calls the native library through JNI. The Java
library (jrxtx-<version>.jar) is published on
https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jrxtx%22[maven
central]. As published on maven central the Java jar file does not
include the native library.

While the Java library is platform independent, the native part of
jRxTx needs to be compiled separately for different processor
architectures and operating systems.  You thus have two options to use
the native library:

. You can install the native library so that the Java virtual machine
  can find it.

. You can rebuild the jrxtx jar file to include the native library of
  your choice.

== Installation of Native Library
    
=== Linux
    
The jRxTx native library is equivalent to the original RXTX native
library. Therefore on Debian based distributions all you have to do is
install the package ‘librxtx-java’:

----
$ sudo apt-get install librxtx-java
----
 
This will install the correct native library. Sometimes you might have
to add a system property so that java finds the jni libs. e.g.:
-Djava.library.path=/usr/lib/jni .

The serial ports /dev/tty* are only accessible to members belonging to
groups dialout and tty. You therefore have to add your user to those
groups. E.g. using:

----
sudo adduser <yourUserName> dialout

sudo adduser <yourUserName> tty
----
    
Afterwards you have to log out and log back in in order for the group
changes to become active.
        

=== Windows

On Windows you need to copy the native library of RXTX for your
specific system to the folder that is in the java.libary.path. To
figure out the actual Java library path in your system, you can write
a Java program that prints System.getProperty(‘java.library.path’).

You can get the native library either from the last distribution
published by rxtx.qbang.org ‘rxtx-2.2pre2-bins.zip’ or you can compile
it on your own from the source code as explained next.

== Build jRxTx

To build jRxTx run the following command:

----
$ ./gradlew [buildNative [-PlibTarget=<the build system e.g. i686-pc-linux-gnu>]] build 
----

The command 'buildNative' will build the native library. The 'build'
command builds the Java jar archive and automatically includes the
native lib in the jar if it was previously built. The -PlibTarget
option is only needed if you want to compile the native library for a
platform other than your host platform.

== API Improvements Over RXTX

Most importantly jRxTx provides an InputStream that behaves in
conformance to the java.io.InputStream interface. Thus it behaves like
Java socket input stream used for IP communication.

The streams provided by the original RXTX have the following
non-conform behavior:
    
* A timeout does not throw an exception but instead returns -1. But
  according to the InputStream interface -1 should only be returned if
  the stream is closed (i.e. the end of stream is reached).

* A thread blocking in InputStream.read() cannot be interrupted by
  closing the associated serial port. Trying to close the serial port
  while another thread is blocking in read() causes the close()
  function to block as well.

The event listener available in RXTX was removed in jRxTx because it
is not needed for data stream reading.
