= jRxTx - Java Serial Communication Library

jRxTx is a Java serial communication library licensed under the
LGPLv2.1 or later. It can be used to communicate using well known
UART-based serial protocols such as RS-232, RS-422 and RS-485. The
goal of jRxTx is to provide a lightweight, intuitive and well
documented API.

jRxTx wraps the popular http://rxtx.qbang.org/[RXTX library] for
which development has been discontinued. In addition to the new API,
the original RXTX API can be accessed through jRxTx. Thus jRxTx can be
used as drop-in replacement for RXTX.

Improvements of jRxTx compared to RXTX:

* Improved API (see explanation below)

* Includes Javadoc

* The Jar file is an OSGi Bundle.

* The Jar file is published on
  https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jrxtx%22[maven
  central].

* The Java build system has been moved to Gradle.

* Optionally add the native libs to the jar and load the libs from the
  jar.

== Using jRxTx

jRxTx consists of a Java library and a native library written in
C. The Java library calls the native library through JNI. The Java
library (jrxtx-<version>.jar) is published on
https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jrxtx%22[maven
central]. As published on maven central it does not include the native
library which thus needs to be installed separately.

=== Installation of Native Library
    
The native part of jRxTx is specific for a certain processor
architecture and operating system. Before you can run an application
that depends on jRxTx you have to install the correct native file for
your OS.
    
==== Linux
    
The jRxTx native library is equivalent to the original RXTX native
library. Therefore on Debian based distributions all you have to do is
install the package ‘librxtx-java’ using your package manager. This
will install the correct native library. Sometimes you might have to
add a system property so that java finds the jni libs. e.g.:
-Djava.library.path=/usr/lib/jni .

The serial ports /dev/tty* are only accessible to members belonging to
groups dialout and tty. You therefore have to add your user to those
groups. E.g. using:

sudo adduser <yourUserName> dialout

sudo adduser <yourUserName> tty

Afterwards you have to log out and log back in in order for the
changes to become active.
        

==== Windows

On Windows you need to copy the native library of RXTX for your
specific system to the folder that is in the java.libary.path. To
figure out the actual Java library path in your system, you can write
a Java program that prints System.getProperty(‘java.library.path’).

You can get the native library either from the last distribution
published by rxtx.qbang.org ‘rxtx-2.2pre2-bins.zip’ or you can compile
it on your own from the source code as explained next.

== Build jRxTx

To build jRxTx run the following command:

----
$ ./gradlew [buildLibs [-PlibTarget=<the build system e.g. i686-pc-linux-gnu>]] build 
----

The command build libs, packs the native library into the jar.

Since jRxTx builds on RXTX, you can also install librxtx-java on
Debian systems, instead of packing the library into the jar, as
mentioned above:

----
$ sudo apt-get install librxtx-java
----

== API Improvements Over RXTX

Most importantly jRxTx provides an InputStream that behaves in
conformance to the java.io.InputStream interface. Thus it behaves like
Java socket input stream used for IP communication.

The streams provided by the original RXTX have the following
non-conform behaviour:
    
* A timeout does not throw an exception but instead returns -1. But
  according to the InputStream interface -1 should only be returned if
  the stream is closed (i.e. the end of stream is reached).

* A thread blocking in InputStream.read() cannot be interrupted by
  closing the associated serial port. Trying to close the serial port
  while another thread is blocking in read() causes the close()
  function to block as well.

The event listener available in RXTX was removed in jRxTx because it
is not needed for data stream reading.
