/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openmuc_serialio_SerialPort */

#ifndef _Included_org_openmuc_serialio_SerialPort
#define _Included_org_openmuc_serialio_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openmuc_serialio_SerialPort
 * Method:    HellWorld
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openmuc_serialio_SerialPort_HellWorld
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openmuc_serialio_SerialPort
 * Method:    Bla
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_openmuc_serialio_SerialPort_Bla
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
