/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openmuc_serialio_SerialPort */

#ifndef _Included_org_openmuc_serialio_SerialPort
#define _Included_org_openmuc_serialio_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openmuc_serialio_SerialPort
 * Method:    getPortNames
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_openmuc_serialio_SerialPort_getPortNames
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
